### ISSUE TITLE
unable to play song after finish event

### ISSUE THREAD

**Issue by nithinoffcl** [katspaugh/wavesurfer.js#1225]
i'm creating a desktop music player using electron when i try to play another song after finish event,i get the following error
Uncaught DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
    at Object.pause (file:///home/nithin/Music_App/node_modules/wavesurfer/dist/wavesurfer.min.js:4:15636)
    at Object.pause (file:///home/nithin/Music_App/node_modules/wavesurfer/dist/wavesurfer.min.js:4:2878)
    at Object.playPause (file:///home/nithin/Music_App/node_modules/wavesurfer/dist/wavesurfer.min.js:4:2949)
    at HTMLButtonElement.onclick (file:///home/nithin/Music_App/index.html:118:52)
pause @ wavesurfer.js:1194
pause @ wavesurfer.js:172
playPause @ wavesurfer.js:176
onclick @ index.html:118
wavesurfer.js:1194 Uncaught DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
    at Object.pause (file:///home/nithin/Music_App/node_modules/wavesurfer/dist/wavesurfer.min.js:4:15636)
    at ScriptProcessorNode.scriptNode.onaudioprocess (file:///home/nithin/Music_App/node_modules/wavesurfer/dist/wavesurfer.min.js:4:12254)
pause @ wavesurfer.js:1194
scriptNode.onaudioprocess @ wavesurfer.js:919.
what should i do??

**Comment by thijstriemstra** [comment]
@nithinoffcl can give some example code that reproduces this problem?

**Comment by thijstriemstra** [comment]
No feedback, closing.
