### ISSUE TITLE
Server Side React with Webpack "window is not defined"

### ISSUE THREAD

**Issue by invisibled** [katspaugh/wavesurfer.js#1334]
Hey There,

I've got a react app using WaveSurfer and loving it. To get an idea of my stack, I'm using Webpack to bundle my node server, which loads the react app server side on first load. Then my regular client side bundle takes over from there, I'm running into an issue with this however... 

When loading a page that imports WaveSurfer `import WaveSurfer from 'wavesurfer.js'` my server code throws an error due to window being undefined, `window is not defined`.

Obviously, node doesn't have `window` so this totally makes sense, I'm just wondering if anybody else has ever experienced this or have any ideas how I can work around this cleanly.

To get around this, I'm requiring the module when the component loads which isn't great, but it does allow me to compile properly, 

```
constructor(props) {
    super(props)

    this.WaveSurfer = require("wavesurfer.js")

    this.state = {
      track : props.data,
      status : 'stopped',
      duration : null,
      currentTime : null
    }
  }
``` 

Any tips or advice on this matter would be great! And please let me know if you need to see any more code, I didn't want to post a wall of code.

**Comment by thijstriemstra** [comment]
where does this window reference come from? sounds like a webpack build issue, not in wavesurfer.js

**Comment by invisibled** [comment]
Here is a dump from the logs when the error occurs. It looks to me like it's coming from wavesurfer.min. I assumed somewhere in the library you guys are attaching something to `window` but since i'm loading my react app server side there wouldn't be any `window` object obviously. This wouldn't ever be a problem client side, it would always get the window reference. I'm just trying to get around it looking for `window` when it loads server side.

```
/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define("WaveSurfer",[],t):"object"==typeof exports?exports.WaveSurfer=t():e.WaveSurfer=t()}("undefined"!=typeof self?self:this,function(){return function(e){function t(n){if(r[n])return r[n].exports;var a=r[n]={i:n,l:!1,exports:{}};return e[n].call(a.exports,a,a.exports,t),a.l=!0,a.exports}var r={};return t.m=e,t.c=r,t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{configurable:!1,enumerable:!0,get:n})},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="",t(t.s=4)}([function(e,t,r){"use strict";function n(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});var a=r(5);Object

ReferenceError: window is not defined
    at Object.defineProperty.value (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:3333)
    at t (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:429)
    at Object.defineProperty.value (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:1604)
    at t (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:429)
    at Object.<anonymous> (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:13643)
    at t (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:429)
    at e.__esModule.default (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:786)
    at /Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:795
    at r.(anonymous function).i (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:143)
    at Object.<anonymous> (/Users/shan/Desktop/lantern/node_modules/wavesurfer.js/dist/wavesurfer.min.js:1:276)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.wavesurfer.js (/Users/shan/Desktop/lantern/.build/server.js:5798:18)
    at __webpack_require__ (/Users/shan/Desktop/lantern/.build/server.js:638:30)
    at fn (/Users/shan/Desktop/lantern/.build/server.js:48:20)
    at Object../app/components/Track.js (/Users/shan/Desktop/lantern/.build/server.js:3372:19)
    at __webpack_require__ (/Users/shan/Desktop/lantern/.build/server.js:638:30)
```

**Comment by thijstriemstra** [comment]
@invisibled wavesurfer.js also uses webpack and since i'm not an expert there, perhaps you can figure out more about the presence (or not) of window when you go through the webpack configs in https://github.com/katspaugh/wavesurfer.js/tree/master/build-config

**Comment by thijstriemstra** [comment]
@invisibled a quick search shows a few references to `window`: https://github.com/katspaugh/wavesurfer.js/search?utf8=%E2%9C%93&q=window&type=
