### ISSUE TITLE
cursor plugin: this.util.withOrientation is not a function

### ISSUE THREAD

**Issue by GaborTorma** [katspaugh/wavesurfer.js#2458]
I have a following error message after upgrading version 6 and use Cursor plugin. 

```
wavesurfer.cursor.js:171 Uncaught TypeError: this.util.withOrientation is not a function
    at CursorPlugin._onReady (wavesurfer.cursor.js:171:1)
    at WaveSurfer.<anonymous> (wavesurfer.cursor.js:235:1)
    at fn (wavesurfer.js:3361:1)
    at wavesurfer.js:3391:1
    at Array.forEach (<anonymous>)
    at WaveSurfer.fireEvent (wavesurfer.js:3390:1)
    at WaveSurfer.loadDecodedBuffer (wavesurfer.js:4942:1)
    at wavesurfer.js:4924:1
    at wavesurfer.js:5151:1
    at OfflineAudioContext.<anonymous> (wavesurfer.js:5821:1)
```

With version 5 or without Cursor plugin I have no errors.

**Comment by thijstriemstra** [comment]
@GaborTorma I would assume the same error appears in the demo, and it doesn't: https://wavesurfer-js.org/example/cursor/index.html

Since you didn't include any wavesurfer config I can't say what's wrong on your side.

**Comment by thijstriemstra** [comment]
no feedback, closing.
