### ISSUE TITLE
Cypress errors

### ISSUE THREAD

**Issue by jgentes** [katspaugh/wavesurfer.js#2934]
I'm not able to run tests successfully, perhaps because I'm on Windows using their new Dev Drive, but I doubt that's the issue. I tried to replicate using https://stackblitz.com/~/github.com/katspaugh/wavesurfer.js but it requires a separate install of cypress and that doesn't seem to be working. 

The errors I'm seeing are:
```
D:\wavesurfer.js [pluginNames ≡ +4 ~4 -0 !]> yarn test

(node:13652) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13652) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.9.0                                                                         │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v18.12.1 (C:\Program Files\nodejs\node.exe)                                    │
  │ Specs:          3 found (basic.cy.js, options.cy.js, regions.cy.js)                            │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  basic.cy.js                                                                     (1 of 3)


  WaveSurfer
    1) "before each" hook for "should instantiate WaveSurfer without errors"


  0 passing (4s)
  1 failing

  1) WaveSurfer
       "before each" hook for "should instantiate WaveSurfer without errors":
     CypressError: Timed out retrying after 4000ms: `cy.its()` errored because the property: `WaveSurfer` does not exist on your subject.

`cy.its()` waited for the specified property `WaveSurfer` to exist, but it never did.

If you do not expect the property `WaveSurfer` to exist, then add an assertion such as:

`cy.wrap({ foo: 'bar' }).its('quux').should('not.exist')`

https://on.cypress.io/its

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `WaveSurfer`
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:135796:80)
      at Object.subjectFn (http://localhost:51183/__cypress/runner/cypress_runner.js:149861:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:51183/__cypress/runner/cypress_runner.js:131091:31)
      at onRetry (http://localhost:51183/__cypress/runner/cypress_runner.js:149852:15)
      at tryCatcher (http://localhost:51183/__cypress/runner/cypress_runner.js:8914:23)
      at Promise.attempt.Promise.try (http://localhost:51183/__cypress/runner/cypress_runner.js:6188:29)
      at whenStable (http://localhost:51183/__cypress/runner/cypress_runner.js:146742:65)
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:146183:14)
      at tryCatcher (http://localhost:51183/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler (http://localhost:51183/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise (http://localhost:51183/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 (http://localhost:51183/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (http://localhost:51183/__cypress/runner/cypress_runner.js:7031:18)
      at Promise._fulfill (http://localhost:51183/__cypress/runner/cypress_runner.js:6975:18)
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:8589:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/basic.cy.js:5:16)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        12                                                                               │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      11                                                                               │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     basic.cy.js                                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  D:\wavesurfer.js\cypress\screenshots\basic.cy.js\WaveSurfer -- should instantiat     (1280x720)
     e WaveSurfer without errors -- before each hook (failed).png


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: 0 seconds

  -  Video output: D:\wavesurfer.js\cypress\videos\basic.cy.js.mp4


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  options.cy.js                                                                   (2 of 3)


  WaveSurfer
    1) "before each" hook for "should use minPxPerSec and hideScrollbar"


  0 passing (4s)
  1 failing

  1) WaveSurfer
       "before each" hook for "should use minPxPerSec and hideScrollbar":
     CypressError: Timed out retrying after 4000ms: `cy.its()` errored because the property: `WaveSurfer` does not exist on your subject.

`cy.its()` waited for the specified property `WaveSurfer` to exist, but it never did.

If you do not expect the property `WaveSurfer` to exist, then add an assertion such as:

`cy.wrap({ foo: 'bar' }).its('quux').should('not.exist')`

https://on.cypress.io/its

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `WaveSurfer`
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:135796:80)
      at Object.subjectFn (http://localhost:51183/__cypress/runner/cypress_runner.js:149861:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:51183/__cypress/runner/cypress_runner.js:131091:31)
      at onRetry (http://localhost:51183/__cypress/runner/cypress_runner.js:149852:15)
      at tryCatcher (http://localhost:51183/__cypress/runner/cypress_runner.js:8914:23)
      at Promise.attempt.Promise.try (http://localhost:51183/__cypress/runner/cypress_runner.js:6188:29)
      at whenStable (http://localhost:51183/__cypress/runner/cypress_runner.js:146742:65)
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:146183:14)
      at tryCatcher (http://localhost:51183/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler (http://localhost:51183/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise (http://localhost:51183/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 (http://localhost:51183/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (http://localhost:51183/__cypress/runner/cypress_runner.js:7031:18)
      at Promise._fulfill (http://localhost:51183/__cypress/runner/cypress_runner.js:6975:18)
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:8589:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/options.cy.js:7:16)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        22                                                                               │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      21                                                                               │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     options.cy.js                                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  D:\wavesurfer.js\cypress\screenshots\options.cy.js\WaveSurfer -- should use minP     (1280x720)
     xPerSec and hideScrollbar -- before each hook (failed).png


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: 0 seconds

  -  Video output: D:\wavesurfer.js\cypress\videos\options.cy.js.mp4


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  regions.cy.js                                                                   (3 of 3)


  WaveSurfer plugins
    1) "before each" hook for "should return all plugins when gatActivePlugins is called"


  0 passing (4s)
  1 failing

  1) WaveSurfer plugins
       "before each" hook for "should return all plugins when gatActivePlugins is called":
     CypressError: Timed out retrying after 4000ms: `cy.its()` errored because the property: `WaveSurfer` does not exist on your subject.

`cy.its()` waited for the specified property `WaveSurfer` to exist, but it never did.

If you do not expect the property `WaveSurfer` to exist, then add an assertion such as:

`cy.wrap({ foo: 'bar' }).its('quux').should('not.exist')`

https://on.cypress.io/its

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `WaveSurfer plugins`
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:135796:80)
      at Object.subjectFn (http://localhost:51183/__cypress/runner/cypress_runner.js:149861:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:51183/__cypress/runner/cypress_runner.js:131091:31)
      at onRetry (http://localhost:51183/__cypress/runner/cypress_runner.js:149852:15)
      at tryCatcher (http://localhost:51183/__cypress/runner/cypress_runner.js:8914:23)
      at Promise.attempt.Promise.try (http://localhost:51183/__cypress/runner/cypress_runner.js:6188:29)
      at whenStable (http://localhost:51183/__cypress/runner/cypress_runner.js:146742:65)
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:146183:14)
      at tryCatcher (http://localhost:51183/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler (http://localhost:51183/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise (http://localhost:51183/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 (http://localhost:51183/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (http://localhost:51183/__cypress/runner/cypress_runner.js:7031:18)
      at Promise._fulfill (http://localhost:51183/__cypress/runner/cypress_runner.js:6975:18)
      at <unknown> (http://localhost:51183/__cypress/runner/cypress_runner.js:8589:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/regions.cy.js:5:16)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        9                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      8                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     regions.cy.js                                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  D:\wavesurfer.js\cypress\screenshots\regions.cy.js\WaveSurfer plugins -- should      (1280x720)
     return all plugins when gatActivePlugins is called -- before each hook (failed).
     png


  (Video)

  -  Started processing:  Compressing to 32 CRF
  -  Finished processing: 0 seconds

  -  Video output: D:\wavesurfer.js\cypress\videos\regions.cy.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ×  basic.cy.js                              00:04       12        -        1        -       11 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  options.cy.js                            00:04       22        -        1        -       21 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  regions.cy.js                            00:04        9        -        1        -        8 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ×  3 of 3 failed (100%)                     00:12       43        -        3        -       40
```

**Comment by katspaugh** [comment]
Did you run `yarn build` before the tests?

**Comment by jgentes** [comment]
ah, thank you :)
