### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MartinDelille** [katspaugh/wavesurfer.js#931]
When setting the zoom to a relatively high value (200 in my case), I have the following error in the console:

```
jquery.js:3846 jQuery.Deferred exception: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined
    at Object.getPeaks (http://localhost:3000/dist/bundle.js:26910:13075)
    at Object.drawBuffer (http://localhost:3000/dist/bundle.js:26910:4873)
    at Object.zoom (http://localhost:3000/dist/bundle.js:26910:5026)
    at HTMLDocument.<anonymous> (http://localhost:3000/dist/bundle.js:127:17)
    at mightThrow (http://localhost:3000/dist/bundle.js:3703:30)
    at process (http://localhost:3000/dist/bundle.js:3771:13) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3846
process @ jquery.js:3642
wavesurfer.min.js:4 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.getPeaks (wavesurfer.min.js:4)
    at Object.drawBuffer (wavesurfer.min.js:4)
    at Object.zoom (wavesurfer.min.js:4)
    at HTMLDocument.<anonymous> (app.js:63)
    at mightThrow (jquery.js:3570)
    at process (jquery.js:3638)
```

Appart from this log, it works fine so there is no big issue there.

My *wavesurfer.js* version: 1.3.0

**Comment by MartinDelille** [comment]
I'll be happy to help you investigate this issue if you want!

**Comment by mspae** [comment]
Can you post your code? (For example into a codepen)

**Comment by thijstriemstra** [comment]
@MartinDelille this shouldn't be too hard to reproduce with some example code.
